(function(config){var fa=navigator.userAgent.toLowerCase(),e=window,ga=document,ha=ga.documentElement;function A(a){return-1!==fa.indexOf(a)}
var oa="ActiveXObject"in e,pa="devicePixelRatio"in e&&1<e.devicePixelRatio||oa&&"matchMedia"in e&&e.matchMedia("(min-resolution:144dpi)")&&e.matchMedia("(min-resolution:144dpi)").matches,qa=A("windows nt"),za=-1!==fa.search(/windows nt [1-5]\./),Aa=-1!==fa.search(/windows nt 5\.[12]/),Ba=za&&!Aa,La=A("windows phone"),Ma=A("macintosh"),Na=A("ipad;"),Ya=Na&&pa,Za=A("ipod touch;"),$a=A("iphone;"),ab=$a||Na||Za,qb=ab&&-1!==fa.search(/ os [456]_/);ab&&fa.search(/ os [4-8]_/);var Eb=ab&&-1!==fa.search(/ os [78]_/);
ab&&A("os 8_");var Fb=A("android"),Gb=-1!==fa.search(/android [123]/),Hb=A("android 4");Fb&&-1===fa.search(/android [1-4]/)||fa.search(/android 4.4/);var Ib=Fb?"android":ab?"ios":qa?"windows":Ma?"mac":"other",Jb=oa&&!e.XMLHttpRequest,Kb=oa&&!ga.querySelector,Lb=oa&&!ga.addEventListener,Mb=oa&&A("ie 9"),Nb=oa&&A("msie 10"),Ob=oa&&A("rv:11");A("edge");
var kc=A("qtweb"),lc=A("ucbrowser"),mc=A("micromessenger"),nc=A("mqqbrowser"),oc=A("baidubrowser"),chrome=A("chrome")&&!mc&&!oc&&!nc,pc=A("firefox"),qc=(Ma||ab)&&A("safari")&&A("version/"),rc=Fb||ab||La||A("mobile")||"undefined"!==typeof orientation,sc=e.navigator&&e.navigator.msPointerEnabled&&!!e.navigator.msMaxTouchPoints,tc=sc||A("touch")||"ontouchstart"in ga,Dc=oa&&"transition"in ha.style,Ec=!!ga.createElementNS&&!!ga.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect,Fc=ga.createElement("canvas"),
Gc=!(!Fc||!Fc.getContext),Hc=!Gc||kc||La||rc&&pc||Mb||qb||Ya||Za||Gb||A("gt-n710")||Ba,Ic=!Hc&&(Hb||Eb||!rc),Jc=Hc||Ic?Hc?"d":"dv":"v",Kc=A("webkit"),Lc="WebKitCSSMatrix"in e&&"m11"in new window.WebKitCSSMatrix,Mc="MozPerspective"in ha.style,Nc="OTransition"in ha.style,Oc=Dc||Lc||Mc||Nc,Pc=void 0!==config[8]?config[8]:!0,Qc=void 0!==config[9]?config[9]:!0,Rc=!Ec&&rc&&Gc,Sc=window.URL||window.webkitURL,Tc=window.Worker&&Sc&&Sc.createObjectURL&&window.Blob&&!oa&&!lc,Uc=!1;try{Uc="undefined"!==typeof e.localStorage}catch(Vc){}
config.j={size:$a?100:Fb?200:800,Zw:Ma,g0:qa,KF:ab,Ke:Fb,uY:Gb,Ax:Ib,wv:oc,l_:nc,TV:qc,lX:mc,Rl:oa,If:Jb,ao:Kb,HZ:Mb,nT:Nb,$c:Lb,pT:oa&&!Ob,ir:Uc,ns:lc,chrome:chrome,TE:pc,W:rc,b_:rc&&Kc,eU:rc&&Lc,a_:rc&&e.opera,ha:pa,zc:tc,wG:sc,jX:Kc,GZ:Dc,kX:Lc,bZ:Mc,e_:Nc,AQ:Oc,Mh:Ec,eo:Gc,KT:Tc,Cf:Pc&&!Hc,LQ:Pc?Jc:"d",ho:Qc&&!!e.WebSocket&&!oc,IU:Rc,MU:Gc||Rc?"c":"d"};var e=window,Wc="http map anip layers overlay0 brender mrender".split(" ");config.Ae="main";config.j.zc&&(Wc+=",touch",config.Ae+="t");config.j.W||(Wc+=",mouse",config.Ae+="m");config.Ae+="c";config.j.Cf&&(config.Ae+="v",Wc+=",vectorlayer,overlay");config[7]&&(Wc+=","+config[7],config.Ae+=config[7].replace(",","").replace(eval("/AMap./gi"),""));Wc+=",sync";config.uI=Wc.split(",");window.AMap=window.AMap||{};window.AMap.$g="1.3.19";var Xc=window.AMap.xy={},Yc=config[2].split(",")[0],Zc=Yc+"/theme/v"+config[4]+"/style1.3.19.css",$c=document.head||document.getElementsByTagName("head")[0];if($c){var ad=document.createElement("link");ad.setAttribute("rel","stylesheet");ad.setAttribute("type","text/css");ad.setAttribute("href",Zc);$c.insertBefore(ad,$c.firstChild)}else document.write("<link rel='stylesheet' href='"+Zc+"'/>");
function bd(a){var b=document,c=b.createElement("script");c.charset="utf-8";c.src=a;(a=b.body||$c)&&a.appendChild(c)}
function cd(){for(var a=Yc+"/maps/main?v="+config[4]+"&key="+config[0]+"&m="+config.uI.join(",")+"&vrs=1.3.19",b=document.getElementsByTagName("script"),c,d=0;d<b.length;d+=1)if(0===b[d].src.indexOf(Yc.split(":")[1]+"/maps?")){c=b[d];break}config[5]||c&&c.async?bd(a):(document.write('<script id="amap_main_js" src=\''+a+"' type='text/javascript'>\x3c/script>"),setTimeout(function(){document.getElementById("amap_main_js")||bd(a)},1))}var dd=(new Date).getTime();
Xc.__load__=function(a){a(config,dd);Xc.__load__=null};try{if(window.localStorage){var ed=window.localStorage["_AMap_"+config.Ae],fd=!1;ed?(ed=JSON.parse(ed),ed.version===window.AMap.$g?(eval(ed.script),Xc.loaded=!0):fd=!0):fd=!0;if(fd)for(var D in window.localStorage)window.localStorage.hasOwnProperty(D)&&0===D.indexOf("_AMap_")&&window.localStorage.removeItem(D)}}catch(gd){}Xc.loaded||(cd(),config.uI=void 0);
})(["3f6a66397ec084e09671fb16a05bcbc9",[118.363373,31.228098,119.241663,32.614363,118.767413,32.041544],"http://webapi.amap.com",1,"1.3",null,"320100","",true,true])